#Movie.create(title: "Rocky", year: 1976, plot:"A small-time boxer gets a supremely rare chance to fight a heavy-weight champion in a bout in which he strives to go the distance for his self-respect.")
#Movie.create(title: "Doctor Zhivago", year: 1965, plot: "The life of a Russian physician and poet who, although married to another, falls in love with a political activist's wife and experiences hardship during World War I and then the October Revolution." )

#Actor.create(first_name: "Angelina", last_name: "Jolie", known_for: "Mr. & Mrs. Smith")
#Actor.create(first_name: "Brad", last_name: "Pitt", known_for: "Seven")
#Actor.create(first_name: "George", last_name: "Clooney", known_for: "Ocean's Eleven")
#Actor.create(first_name: "Matt", last_name: "Damon", known_for: "Good Will Hunting")
#Actor.create(first_name: "Julia", last_name: "Roberts", known_for: "Pretty Woman")
#Actor.create(first_name: "Susan", last_name: "Sarandon", known_for: "Thelma & Louise")

#Actor.create(first_name: "Angelina", last_name: "Jolie", known_for: "Hackers")
#Actor.create(first_name: "Brad", last_name: "Pitt", known_for: "Ocean's Eleven")

#Movie.create(title: "Love.net", year: 2011, plot:"Follows the parallel stories of a number of characters who are trying to change their lives via the Internet or are simply having fun online.", english: FALSE)
#Movie.create(title: "Yesterday", year: 1988, plot:"The 1960s was the time of Beatles and Rolling Stones, the time of sexual revolution. These events have their echo in Bulgarian English-learning school. The school order provokes a protest of the students due to the narrow-minded teachers.", director: "Ivan Andonov", english: FALSE)
#Movie.create(title: "All for love", year: 1986, plot:"This is a film about the general collision between the generations. The film tells us the story of a 14 year old boy and his father, and the way they fight over all the problems.", director: "Nikolai Volev", english: FALSE)
#Movie.create(title: "Pretty Woman", year: 1990, plot:"Pretty Woman is a 1990 American romantic comedy film directed by Garry Marshall, from a screenplay by J. F. Lawton. The film stars Richard Gere and Julia Roberts.", director: "Garry Marshall", english: TRUE)
#Movie.create(title: "G. I. Jane", year: 1997, plot:"In response to political pressure from Senator Lillian DeHaven (Anne Bancroft), the U.S. Navy begins a program that would allow for the eventual integration of women into its services.", director: "Ridley Scott", english: TRUE)
#Movie.create(title: "Thelma & Louise", year: 1991, plot:"Housewife Thelma (Geena Davis) joins her friend Louise (Susan Sarandon), an independent waitress, on a short fishing trip. However, their trip becomes a flight from the law", director: "Ridley Scott", english: TRUE)
#Movie.create(title: "Ocean's Eleven", year: 2001, plot:"Dapper Danny Ocean (George Clooney) is a man of action. Less than 24 hours into his parole from a New Jersey penitentiary, the wry, charismatic thief is already rolling out his next plan.", director: "Steven Soderbergh", english: TRUE)
#Movie.create(title: "Seven", year: 1995, plot:"When retiring police Detective William Somerset (Morgan Freeman) tackles a final case with the aid of newly transferred David Mills (Brad Pitt), they discover a number of elaborate and grizzly murders.", director: "David Fincher", english: TRUE)
#Movie.create(title: "Hackers", year: 1995, plot:"A teenage hacker finds himself framed for the theft of millions of dollars from a major corporation.", director: "Iain Softley", english: TRUE)
#Movie.create(title: "Mr. & Mrs. Smith", year: 2005, plot:"John (Brad Pitt) and Jane Smith (Angelina Jolie), a couple in a stagnating marriage, live a deceptively mundane existence. However, each has been hiding a secret from the other: they are assassins working for adversarial agencies.", director: "Doug Liman", english: TRUE)

# Genre.create(name: "Comedy")
# Genre.create(name: "Action")
# Genre.create(name: "Drama")
# Genre.create(name: "Thriller")
# Genre.create(name: "Adventure")
# Genre.create(name: "Romance")
# Genre.create(name: "Crime")

# MovieGenre.create(genre_id: 4, movie_id: 1)
# MovieGenre.create(genre_id: 4, movie_id: 18)
# MovieGenre.create(genre_id: 6, movie_id: 18)
# MovieGenre.create(genre_id: 4, movie_id: 16)
# MovieGenre.create(genre_id: 7, movie_id: 16)
# MovieGenre.create(genre_id: 2, movie_id: 15)
# MovieGenre.create(genre_id: 4, movie_id: 15)
# MovieGenre.create(genre_id: 4, movie_id: 14)
# MovieGenre.create(genre_id: 1, movie_id: 14)
# MovieGenre.create(genre_id: 4, movie_id: 13)
# MovieGenre.create(genre_id: 2, movie_id: 13)
# MovieGenre.create(genre_id: 1, movie_id: 12)
# MovieGenre.create(genre_id: 6, movie_id: 12)